### ISSUE TITLE
5G NSA DCNR - Security mode command malformed

### ISSUE THREAD

**Issue by lulloaX** [omec-project/Nucleus#121]
**Issue Description**
Currently we already deployed OMEC Core using the follow images for Control plane `(omec-control-plane-0.7.2)` :
```
  tags:
    init: docker.io/omecproject/pod-init:1.0.0
    hssdb: registry.aetherproject.org/proxy/omecproject/c3po-hssdb:master-9a5f565
    hss: registry.aetherproject.org/proxy/omecproject/c3po-hss:master-9a5f565
    mme: registry.aetherproject.org/proxy/omecproject/nucleus:master-86d2678
    spgwc: registry.aetherproject.org/omecproject/spgw:master-6aad2f2
    pcrf: registry.aetherproject.org/proxy/omecproject/c3po-pcrf:pcrf-b29af70
    pcrfdb: registry.aetherproject.org/proxy/omecproject/c3po-pcrfdb:pcrf-b29af70
    config4g: registry.aetherproject.org/omecproject/5gc-webui:onf-release3.0.5-bf0b54f
    depCheck: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
```

During 3x Dual connectivity Attach procedure we obtained a Malformed package from MME instead of `Security mode command` as bellow image show. 

![image](https://user-images.githubusercontent.com/28659806/134583321-f8b4af60-5d17-4864-a671-8798b9d765d5.png)

On `Attach Request` message UE sends the mandatory IEs according to standard to support 5G NSA 3x attach:
- DCNR bit enabled on `UE Network Capability`
- `UE Additional security capability` IE

![image](https://user-images.githubusercontent.com/28659806/134584766-8db4af70-b4a8-4497-8966-820cde2b259d.png)
![image](https://user-images.githubusercontent.com/28659806/134584822-b5f20c07-0766-4549-8716-266471fe95d6.png)

For this Attach procedure, we tried it using differents types: `EPS Only` and `Combined attach`, but for all obtained the same malformed package as result. 
After check the `s1ap` container logs we found that it reports an error, we think is related to the size of message, and  checking the repository code we think the issue happens on some hardcoded lines in `secreq_processing` function that finally sends the malformed message by sctp.

![image](https://user-images.githubusercontent.com/28659806/134600188-41a81a9e-561d-4ef3-a1a7-02dfba64968a.png)

So, please your support to check:
1. Why this malformed package is sent by MME? Is this OMEC control plane version supporting 5G NSA?
2. Do we need perform some additional configurations on OMEC Core?

I attached the .pcap file and logs for s1ap, s6a and mme services.

**Expected Behavior**
MME should send the `Security mode command` message to eNodeB and it should include `Replayed additional security capabilities` IE.

**Additional context**

- Attach trace (.pcap file):
[Attach_s1ap.zip](https://github.com/omec-project/Nucleus/files/7221434/Attach_s1ap.zip)

- s1ap, s6a and mme logs during the  attach procedure:
[logs.zip](https://github.com/omec-project/Nucleus/files/7221437/logs.zip)
